#! /bin/bash

# Node key
cat $1 | awk '/BEGIN PRIVATE KEY/,/END PRIVATE KEY/' > $2.key

# Node certificate
openssl crl2pkcs7 -nocrl -certfile $1 | openssl pkcs7 -print_certs | awk '/subject.*CN=.*.com/,/END CERTIFICATE/' | tail -n +3 > $2.crt

# Intermediate certificate
openssl crl2pkcs7 -nocrl -certfile $1 | openssl pkcs7 -print_certs | awk '/subject.*CN=DC1IntermediateCA01/,/END CERTIFICATE/' | tail -n +3 > intermediate.crt

# Root certificate
openssl crl2pkcs7 -nocrl -certfile $1 | openssl pkcs7 -print_certs | awk '/subject.*CN=DC1RootCA01/,/END CERTIFICATE/' | tail -n +3 > rootca.crt


cat intermediate.crt rootca.crt > trustca.crt
cat $2.crt trustca.crt > $2.chain.crt

openssl pkcs12 -export -name $2 \
      -in $2.chain.crt -inkey $2.key \
      -out $2.keystore.pkcs12 \
      -password pass:casspass123


keytool -delete -import -noprompt -alias trustca \
   -storetype PKCS12 \
   -file trustca.crt \
   -keystore truststore.pkcs12 \
   -storepass casspass123